TrainX/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TrainX.Models;

namespace TrainX.Controllers
{

	public class HomeController : Controller
	{
		private readonly TrainXContext _context;

		public HomeController(TrainXContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			var sport = _context.Sports.ToList();
			return View(sport);
		}

		public IActionResult Program()
		{
			var sport = _context.Sports.ToList();
			return View(sport);
		}

		public IActionResult Classes()
		{
			return View();
		}

		public IActionResult Contact()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

TrainX/Controllers/VideoController.cs
using Microsoft.AspNetCore.Mvc;
using TrainX.Models;

namespace TrainX.Controllers
{
	public class VideoController : Controller
	{
		private readonly TrainXContext _context;

		public VideoController(TrainXContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			var video = _context.Videos.ToList();
			return View(video);
		}
	}
}

TrainX/Views/Home/Classes.cshtml
@{
    ViewData["Title"] = "Classes";
}

<!-- ***** Our Classes Start ***** -->
    <section class="section" id="our-classes">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading">
                        <h2>Our <em>Classes</em></h2>
                        <img src="~/assets/images/line-dec.png" alt="">
                        <p>The site provides you with variations of classes in different categories.they are fun way to lose weight and get in shape fast. You can start your journey now</p>
                    </div>
                </div>
            </div>
            <div class="row" id="tabs">
                <div class="col-lg-4">
                    <ul>
                        <li><a href='#tabs-1'><img src="~/assets/images/tabs-first-icon.png" alt="">Weight lifting Class</a></li>
                        <li><a href='#tabs-2'><img src="~/assets/images/tabs-first-icon.png" alt="">Cardio Class</a></li>
                        <li><a href='#tabs-3'><img src="~/assets/images/tabs-first-icon.png" alt="">Fitness Class</a></li>
                        <li><a href='#tabs-4'><img src="~/assets/images/tabs-first-icon.png" alt="">Yoga Class</a></li>
                    <div class="main-rounded-button"><a href="#schedule">View All Schedules</a></div>
                    </ul>
                </div>
                <div class="col-lg-8">
                <section class='tabs-content'>
                    <article id='tabs-1'>
                        <img src="~/assets/images/training-image-01.jpg" alt="First Class">
                        <h4>Weight lifting Class</h4>
                        <p>Weight lifting is a type of strength training that involves lifting and lowering weights, such as barbells, dumbbells, or kettlebells. Weight lifting can help improve muscle mass, strength, endurance, and power. Weight lifting can also benefit your health by reducing the risk of chronic diseases, such as diabetes, heart disease, and osteoporosis.</p>
                        <div class="main-button">
                            <a href="#schedule">View Schedule</a>
                        </div>
                    </article>
                    <article id='tabs-2'>
                        <img src="~/assets/images/training-image-02.jpg" alt="Second Training">
                        <h4>Cardio Class</h4>
                        <p>Cardio Sport is a comprehensive training system that will get you into the best shape of your life.This unique method is designed to excite and inspire people who love team sports (and music). The technical definition of Cardio Sport is comprehensive athletic conditioning integration.</p>
                        <div class="main-button">
                            <a href="#schedule">View Schedule</a>
                        </div>
                    </article>
                    <article id='tabs-3'>
                        <img src="~/assets/images/training-image-03.jpg" alt="Third Class">
                        <h4>Fitness Class</h4>
                        <p>Physical fitness is a state of health and well-being and, more specifically, the ability to perform aspects of sports, occupations and daily activities. Physical fitness is generally achieved through proper nutrition, moderate-vigorous physical exercise, and sufficient rest along with a formal recovery plan.</p>
                        <div class="main-button">
                            <a href="#schedule">View Schedule</a>
                        </div>
                    </article>
                    <article id='tabs-4'>
                        <img src="~/assets/images/training-image-04.jpg" alt="Fourth Training">
                        <h4>Yoga Class</h4>
                        <p>Yoga is an ancient practice that involves physical poses, concentration, and deep breathing. Yoga aims to promote physical and mental well-being and spiritual connection. There are several types of yoga and each one has its own characteristics.</p>
                        <div class="main-button">
                            <a href="#schedule">View Schedule</a>
                        </div>
                    </article>
                </section>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Our Classes End ***** -->
    
    <section class="section" id="schedule">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="section-heading dark-bg">
                        <h2>Classes <em>Schedule</em></h2>
                        <img src="~/assets/images/line-dec.png" alt="">
                        <p>Nunc urna sem, laoreet ut metus id, aliquet consequat magna. Sed viverra ipsum dolor, ultricies fermentum massa consequat eu.</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="filters">
                        <ul class="schedule-filter">
                            <li class="active" data-tsfilter="monday">Monday</li>
                            <li data-tsfilter="tuesday">Tuesday</li>
                            <li data-tsfilter="wednesday">Wednesday</li>
                            <li data-tsfilter="thursday">Thursday</li>
                            <li data-tsfilter="friday">Friday</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-10 offset-lg-1">
                    <div class="schedule-table filtering">
                        <table>
                            <tbody>
                                <tr>
                                    <td class="day-time">Fitness Class</td>
                                    <td class="monday ts-item show" data-tsmeta="monday">10:00AM - 11:30AM</td>
                                    <td class="tuesday ts-item" data-tsmeta="tuesday">2:00PM - 3:30PM</td>
                                    <td>William G. Stewart</td>
                                </tr>
                                <tr>
                                    <td class="day-time">Muscle Training</td>
                                    <td class="friday ts-item" data-tsmeta="friday">10:00AM - 11:30AM</td>
                                    <td class="thursday friday ts-item" data-tsmeta="thursday" data-tsmeta="friday">2:00PM - 3:30PM</td>
                                    <td>Paul D. Newman</td>
                                </tr>
                                <tr>
                                    <td class="day-time">Body Building</td>
                                    <td class="tuesday ts-item" data-tsmeta="tuesday">10:00AM - 11:30AM</td>
                                    <td class="monday ts-item show" data-tsmeta="monday">2:00PM - 3:30PM</td>
                                    <td>Boyd C. Harris</td>
                                </tr>
                                <tr>
                                    <td class="day-time">Yoga Training Class</td>
                                    <td class="wednesday ts-item" data-tsmeta="wednesday">10:00AM - 11:30AM</td>
                                    <td class="friday ts-item" data-tsmeta="friday">2:00PM - 3:30PM</td>
                                    <td>Hector T. Daigle</td>
                                </tr>
                                <tr>
                                    <td class="day-time">Advanced Training</td>
                                    <td class="thursday ts-item" data-tsmeta="thursday">10:00AM - 11:30AM</td>
                                    <td class="wednesday ts-item" data-tsmeta="wednesday">2:00PM - 3:30PM</td>
                                    <td>Bret D. Bowers</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>

TrainX/Views/Home/Contact.cshtml
@{
ViewData["Title"] = "Contact";
}
<!-- bradcam_area -->
<div class="bradcam_area">
    <div class="single_bradcam  d-flex align-items-center bradcam_bg_2 overlay">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-xl-9">
                    <div class="bradcam_text text-center">
                        <h3>contact</h3>
                    </div>
                </div> 
            </div>
        </div>
    </div>
</div>
<!-- bradcam_area end -->
<!-- team_area_start  -->
<div class="team_area team_bg_1 overlay2">
    <div class="container">
            <div class="row">
                    <div class="col-xl-12">
                        <div class="section_title text-center mb-73">
                            <h3>Our Trainers</h3>
                            <p>There are many variations of passages of lorem Ipsum available, but the majority <br> have suffered alteration.</p>
                        </div>
                    </div>
                </div>
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="single_team">
                    <div class="team_thumb">
                        <img src="~/assets/img/team/1.png" alt="">
                        <div class="team_hover">
                            <div class="hover_inner text-center">
                                <ul>
                                    <li><a href="#"> <i class="fa fa-facebook"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-twitter"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-instagram"></i> </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="team_title text-center">
                        <h3>Jessica Mino</h3>
                        <p>Woman Trainer</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single_team">
                    <div class="team_thumb">
                        <img src="~/assets/img/team/2.png" alt="">
                        <div class="team_hover">
                            <div class="hover_inner text-center">
                                <ul>
                                    <li><a href="#"> <i class="fa fa-facebook"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-twitter"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-instagram"></i> </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="team_title text-center">
                        <h3>Amit Khan</h3>
                        <p>Men Trainer</p>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single_team">
                    <div class="team_thumb">
                        <img src="~/assets/img/team/3.png" alt="">
                        <div class="team_hover">
                            <div class="hover_inner text-center">
                                <ul>
                                    <li><a href="#"> <i class="fa fa-facebook"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-twitter"></i> </a></li>
                                    <li><a href="#"> <i class="fa fa-instagram"></i> </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="team_title text-center">
                        <h3>Paulo Rolac</h3>
                        <p>Men Trainer</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- team_area_end  -->

<!-- ***** Contact Us Area Starts ***** -->
    <section class="section" id="contact-us">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-xs-12">
                    <div id="map">
                      <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="600px" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-xs-12">
                    <div class="contact-form">
                        <form id="contact" action="" method="post">
                            <div class="row">
                            <div class="col-md-6 col-sm-12">
                                <fieldset>
                                    <input name="name" type="text" id="name" placeholder="Your Name*" required="">
                                </fieldset>
                            </div>
                            <div class="col-md-6 col-sm-12">
                                <fieldset>
                                    <input name="email" type="text" id="email"  placeholder="Your Email*" required="">
                                </fieldset>
                            </div>
                            <div class="col-md-12 col-sm-12">
                                <fieldset>
                                    <input name="subject" type="text" id="subject" placeholder="Subject">
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <textarea name="message" rows="6" id="message" placeholder="Message*" required=""></textarea>
                                </fieldset>
                            </div>
                            <div class="col-lg-12">
                                <fieldset>
                                    <button type="submit" id="form-submit" class="main-button">Send Message</button>
                                </fieldset>
                            </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Contact Us Area Ends ***** -->

TrainX/Views/Home/Program.cshtml
@model IEnumerable<Sport>

@{
    ViewData["Title"] = "Program";
}

@section Styles{

}

<!-- ***** Call to Action Start ***** -->
<section class="section mb-5" id="call-to-action">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <div class="cta-content">
                    <div class="section-heading">
                        <h2>Choose <em>Program</em></h2>
                        <img src="~/assets/images/line-dec.png" alt="waves">
                        <p>TrainX website provides variety of programs with different levels. You can choose the desired program.The pain you feel today will be the strength you feel tomorrow.From here. Enjoy</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ***** Call to Action End ***** -->

<!-- ***** Features Item Start ***** -->
<section class="section" id="features">
    <div class="container">
        <div class="row"> 
            @foreach (var item in Model)
            {
                <div class="col-4 mb-5">
                    <div class="cardstyle card">
                        <img style="height: 250px" src="@item.ImageUrl" class="card-img-top" alt="First One">
                        <div class="card-body textcolor">
                            <h5 class="card-title">@item.Name</h5>
                            <p class="card-text">@item.Description</p>
                            <a asp-controller="Video" asp-action="Index" class="btn">Discover More</a>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<!-- ***** Features Item End ***** -->

<div class="offer_area offer_bg">
    <div class="container">
        <div class="row justify-content-end">
            <div class="col-lg-6">
                <div class="offer_text">
                    <h4>A Big Offer for <br>
                            This Summer</h4>
                    <h3>50% Off</h3>
                    <p>Before your body, your mind comes to the gym.Get the offer now</p>
                    <a asp-area="Identity" asp-page="/Account/Login" class="boxed-btn3">Join Now</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="priscing_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="single_prising text-center">
                    <div class="prising_header">
                            <h3>Beginner</h3>
                            <span>$45</span>
                    </div>
                    <div class="pricing_body">
                        <ul>
                            <li>24h unlimited access</li>
                            <li>Trainer Advice</li>
                            <li class="off-color">Locker + Bathroom</li>
                            <li class="off-color">Personal trainer</li>
                        </ul>
                    </div>
                    <div class="pricing_btn">
                        <a asp-area="Identity" asp-page="/Account/Login" class="boxed-btn3">Join Now</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single_prising text-center">
                    <div class="prising_header">
                            <h3>Expert</h3>
                            <span>$45</span>
                    </div>
                    <div class="pricing_body">
                        <ul>
                            <li>24h unlimited access</li>
                            <li>Trainer Advice</li>
                            <li class="off-color">Locker + Bathroom</li>
                            <li class="off-color">Personal trainer</li>
                        </ul>
                    </div>
                    <div class="pricing_btn">
                        <a asp-area="Identity" asp-page="/Account/Login" class="boxed-btn3">Join Now</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="single_prising text-center">
                    <div class="prising_header">
                            <h3>Pro</h3>
                            <span>$45</span>
                    </div>
                    <div class="pricing_body">
                        <ul>
                            <li>24h unlimited access</li>
                            <li>Trainer Advice</li>
                            <li class="off-color">Locker + Bathroom</li>
                            <li class="off-color">Personal trainer</li>
                        </ul>
                    </div>
                    <div class="pricing_btn">
                        <a asp-area="Identity" asp-page="/Account/Login" class="boxed-btn3">Join Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="features_area">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="section_title text-center mb-73">
                    <h3>Our Features</h3>
                    <p>we have more features that are not in any other application which makes us unique among others, with more correct<br /> calculations and coaching support all for free and in the hand of every user.</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="single_feature text-center mb-73">
                    <div class="icon">
                        <img src="~/assets/img/svg_icon/1.svg" alt="">
                    </div>
                    <h4>Weightlifting</h4>
                    <p>Weight lifting is a type of strength training that involves lifting and lowering weights, such as barbells, dumbbells, or kettlebells.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single_feature text-center">
                    <div class="icon">
                        <img src="~/assets/img/svg_icon/2.svg" alt="">
                    </div>
                    <h4>Specific Muscles</h4>
                    <p>Muscle fitness means having muscles that can lift heavier objects or muscles that will work longer before becoming exhausted</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single_feature text-center">
                    <div class="icon">
                        <img src="~/assets/img/svg_icon/3.svg" alt="">
                    </div>
                    <h4>Flex Your Muscles</h4>
                    <p>Muscle fitness Weightlifting is an athletic discipline which requires lifting of heavy weights in a progressive manner</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="single_feature text-center">
                    <div class="icon">
                        <img src="~/assets/img/svg_icon/4.svg" alt="">
                    </div>
                    <h4>Cardio Exercises</h4>
                    <p>Cardio Sport is a comprehensive training system that will get you into the best shape of your life.</p>
                </div>
            </div>
        </div>
    </div>
</div>